### ISSUE TITLE
The library is not supported to decompress using ZlibStreamFlavor (DEFLATE)

### ISSUE THREAD

**Issue by sregula-net** [jstedfast/Ionic.Zlib#3]
Hi ,

The default implementation to decompress the stream using  ZLIB = 1950. We have situation to decompress using  DEFLATE = 1951. 

To support for all three types of decompression , we can create new constructor like as follows.

public ZlibStream(Stream stream, CompressionMode mode, CompressionLevel level, bool leaveOpen, ZlibStreamFlavor zlibStreamFlavor )
        {
            _baseStream = new ZlibBaseStream(stream, mode, level, zlibStreamFlavor, leaveOpen);
        }

Please let me know if you need Pull Request. I can create one and will share with you.

Thanks
Satya

**Comment by jstedfast** [comment]
Are you aware that this is not the official repo? I just don't want you to waste your time fixing an 8-year-old fork when the official version might already have what you need.

**Comment by sregula-net** [comment]
Thanks for info.

The issue is not fixed in latest version but i will check in offical repo.
